name: pfadfinden/text-image-mask
typeName: pfadfinden_textimagemask
group: default
prefixFields: true
prefixType: vendor
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: bodytext
    useExistingField: true
    enableRichtext: true
  - identifier: image
    useExistingField: true
    maxitems: 1
    minitems: 1
  - identifier: Pfadfinden/Mask
    type: Basic
basics:
  - TYPO3/Appearance
  - TYPO3/Links
