name: pfadfinden/small-cta-image
typeName: pfadfinden_smallctaimage
group: default
prefixFields: true
prefixType: vendor
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: subheader
    useExistingField: true
  - identifier: bodytext
    useExistingField: true
    enableRichtext: true
  - identifier: image
    useExistingField: true
    maxitems: 1
    minitems: 1
  - identifier: mask
    type: Select
    renderType: selectSingle
    default: 'mask_001'
    items:
      - label: 'Mask 01'
        value: mask_001
      - label: 'Mask 02'
        value: mask_002
      - label: 'Mask 03'
        value: mask_003
basics:
  - TYPO3/Appearance
  - TYPO3/Links

