name: pfadfinden/text-mask-image
typeName: pfadfinden_textmaskimage
group: default
prefixFields: true
prefixType: vendor
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: bodytext
    useExistingField: true
    enableRichtext: true
  - identifier: image
    useExistingField: true
    maxitems: 1
    minitems: 1
  - identifier: mask
    type: Select
    renderType: selectSingle
  - identifier: Pfadfinden/Icon
    type: Basic
basics:
  - TYPO3/Appearance
  - TYPO3/Links
